name: OpenData Workfow for FAIR Data
on:
  push:
    tags:
      - '*'
  #workflow_dispatch:

jobs:
  build:
    uses: robert-koch-institut/OpenData-Workflows/.github/workflows/OpenData_Workflows.yml@main
    with:
      # General Variables 
      ZENODOJSON_PATH: Metadata/zenodo.json
    
      # Push to OpenCoDE
      OPENCODE_ACTIVE: true
      OPENCODE_GROUPID: 2781
      OPENCODE_ACCESS_USER: RKIOpenData
      
      # Push to GovData Repositoy
      GOVDATA_ACTIVE: false
      GOVDATA_DESTINATION_REPO: RKIOpenData/Metadaten_fuer_GovData
      
      # Push to NFDI4Health
      NFDI4HEALTH_ACTIVE: false
      
      #Build Open Data Website
      WEBSITE_ACTIVE: false

      #Update Github Details
      GITHUB_DETAILS_ACTIVE: true
          
      
    secrets:

      # Token from OpenCoDE Account
      OPENCODE_TOKEN: ${{secrets.OPENCODE_TOKEN}}
      
      # Github Token
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      GITHUB_METADATA_TOKEN: ${{secrets.ADMINISTRATION_TOKEN}}
